"""initial_schema_with_tenancy_and_indexes

Revision ID: ced8fcdd6f45
Revises: 
Create Date: 2026-10-08 12:36:27.875258

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ced8fcdd6f45'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_mode_configs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('model_provider', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('retrieval_threshold', sa.Float(), nullable=True),
    sa.Column('max_search_results', sa.Integer(), nullable=True),
    sa.Column('enable_recommendations', sa.Boolean(), nullable=True),
    sa.Column('enable_comparisons', sa.Boolean(), nullable=True),
    sa.Column('enable_cart_actions', sa.Boolean(), nullable=True),
    sa.Column('system_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_mode_configs_id'), 'ai_mode_configs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_mode_configs_workspace_id'), 'ai_mode_configs', ['workspace_id'], unique=True)
    op.create_table('deployments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('allowed_domains', sa.JSON(), nullable=True),
    sa.Column('theme_json', sa.JSON(), nullable=True),
    sa.Column('branding_json', sa.JSON(), nullable=True),
    sa.Column('embed_code', sa.Text(), nullable=True),
    sa.Column('total_conversations', sa.Integer(), nullable=True),
    sa.Column('total_product_clicks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_id'), 'deployments', ['id'], unique=False)
    op.create_index(op.f('ix_deployments_workspace_id'), 'deployments', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_agent_policies_agent_id'), 'agent_policies', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_versions_agent_id'), 'agent_versions', ['agent_id'], unique=False)
    op.create_index('idx_agent_tenant', 'agents', ['workspace_id', 'id'], unique=False)
    op.create_index(op.f('ix_agents_workspace_id'), 'agents', ['workspace_id'], unique=False)
    op.add_column('audit_logs', sa.Column('workspace_id', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.add_column('commerce_carts', sa.Column('workspace_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_commerce_carts_workspace_id'), 'commerce_carts', ['workspace_id'], unique=False)
    op.add_column('commerce_orders', sa.Column('order_number', sa.String(length=100), nullable=False))
    op.add_column('commerce_orders', sa.Column('customer_id', sa.String(length=64), nullable=True))
    op.add_column('commerce_orders', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('commerce_orders', sa.Column('payment_status', sa.String(length=50), nullable=True))
    op.add_column('commerce_orders', sa.Column('fulfillment_status', sa.String(length=50), nullable=True))
    op.add_column('commerce_orders', sa.Column('shipping_address', sa.Text(), nullable=True))
    op.add_column('commerce_orders', sa.Column('tracking_number', sa.String(length=100), nullable=True))
    op.add_column('commerce_orders', sa.Column('carrier', sa.String(length=100), nullable=True))
    op.add_column('commerce_orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index('idx_order_tenant_email', 'commerce_orders', ['workspace_id', 'customer_email'], unique=False)
    op.create_index('idx_order_tenant_number', 'commerce_orders', ['workspace_id', 'order_number'], unique=False)
    op.create_index(op.f('ix_commerce_orders_customer_email'), 'commerce_orders', ['customer_email'], unique=False)
    op.create_index(op.f('ix_commerce_orders_order_number'), 'commerce_orders', ['order_number'], unique=False)
    op.create_index(op.f('ix_commerce_orders_workspace_id'), 'commerce_orders', ['workspace_id'], unique=False)
    op.add_column('commerce_products', sa.Column('compare_at_price', sa.Float(), nullable=True))
    op.add_column('commerce_products', sa.Column('sku', sa.String(length=100), nullable=True))
    op.add_column('commerce_products', sa.Column('images_json', sa.JSON(), nullable=True))
    op.add_column('commerce_products', sa.Column('tags_json', sa.JSON(), nullable=True))
    op.add_column('commerce_products', sa.Column('variants_json', sa.JSON(), nullable=True))
    op.add_column('commerce_products', sa.Column('attributes_json', sa.JSON(), nullable=True))
    op.add_column('commerce_products', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('commerce_products', sa.Column('in_stock', sa.Boolean(), nullable=True))
    op.add_column('commerce_products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index('idx_prod_tenant_cat', 'commerce_products', ['workspace_id', 'category'], unique=False)
    op.create_index('idx_prod_tenant_id', 'commerce_products', ['workspace_id', 'id'], unique=False)
    op.create_index('idx_prod_tenant_sku', 'commerce_products', ['workspace_id', 'sku'], unique=False)
    op.create_index(op.f('ix_commerce_products_category'), 'commerce_products', ['category'], unique=False)
    op.create_index(op.f('ix_commerce_products_sku'), 'commerce_products', ['sku'], unique=False)
    op.create_index(op.f('ix_commerce_products_workspace_id'), 'commerce_products', ['workspace_id'], unique=False)
    op.add_column('conversations', sa.Column('workspace_id', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_conversations_agent_id'), 'conversations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_integrations_workspace_id'), 'integrations', ['workspace_id'], unique=False)
    op.add_column('knowledge_chunks', sa.Column('workspace_id', sa.String(length=64), nullable=False))
    op.create_index('idx_chunk_tenant', 'knowledge_chunks', ['workspace_id', 'id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_doc_id'), 'knowledge_chunks', ['doc_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_workspace_id'), 'knowledge_chunks', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_source_id'), 'knowledge_documents', ['source_id'], unique=False)
    op.create_index('idx_ks_tenant', 'knowledge_sources', ['workspace_id', 'id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_workspace_id'), 'knowledge_sources', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_ws_member_tenant_user', 'workspace_members', ['workspace_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_index('idx_ws_member_tenant_user', table_name='workspace_members')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_knowledge_sources_workspace_id'), table_name='knowledge_sources')
    op.drop_index('idx_ks_tenant', table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_documents_source_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_chunks_workspace_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_doc_id'), table_name='knowledge_chunks')
    op.drop_index('idx_chunk_tenant', table_name='knowledge_chunks')
    op.drop_column('knowledge_chunks', 'workspace_id')
    op.drop_index(op.f('ix_integrations_workspace_id'), table_name='integrations')
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_agent_id'), table_name='conversations')
    op.drop_column('conversations', 'workspace_id')
    op.drop_index(op.f('ix_commerce_products_workspace_id'), table_name='commerce_products')
    op.drop_index(op.f('ix_commerce_products_sku'), table_name='commerce_products')
    op.drop_index(op.f('ix_commerce_products_category'), table_name='commerce_products')
    op.drop_index('idx_prod_tenant_sku', table_name='commerce_products')
    op.drop_index('idx_prod_tenant_id', table_name='commerce_products')
    op.drop_index('idx_prod_tenant_cat', table_name='commerce_products')
    op.drop_column('commerce_products', 'updated_at')
    op.drop_column('commerce_products', 'in_stock')
    op.drop_column('commerce_products', 'source_url')
    op.drop_column('commerce_products', 'attributes_json')
    op.drop_column('commerce_products', 'variants_json')
    op.drop_column('commerce_products', 'tags_json')
    op.drop_column('commerce_products', 'images_json')
    op.drop_column('commerce_products', 'sku')
    op.drop_column('commerce_products', 'compare_at_price')
    op.drop_index(op.f('ix_commerce_orders_workspace_id'), table_name='commerce_orders')
    op.drop_index(op.f('ix_commerce_orders_order_number'), table_name='commerce_orders')
    op.drop_index(op.f('ix_commerce_orders_customer_email'), table_name='commerce_orders')
    op.drop_index('idx_order_tenant_number', table_name='commerce_orders')
    op.drop_index('idx_order_tenant_email', table_name='commerce_orders')
    op.drop_column('commerce_orders', 'updated_at')
    op.drop_column('commerce_orders', 'carrier')
    op.drop_column('commerce_orders', 'tracking_number')
    op.drop_column('commerce_orders', 'shipping_address')
    op.drop_column('commerce_orders', 'fulfillment_status')
    op.drop_column('commerce_orders', 'payment_status')
    op.drop_column('commerce_orders', 'customer_name')
    op.drop_column('commerce_orders', 'customer_id')
    op.drop_column('commerce_orders', 'order_number')
    op.drop_index(op.f('ix_commerce_carts_workspace_id'), table_name='commerce_carts')
    op.drop_column('commerce_carts', 'workspace_id')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_column('audit_logs', 'workspace_id')
    op.drop_index(op.f('ix_agents_workspace_id'), table_name='agents')
    op.drop_index('idx_agent_tenant', table_name='agents')
    op.drop_index(op.f('ix_agent_versions_agent_id'), table_name='agent_versions')
    op.drop_index(op.f('ix_agent_policies_agent_id'), table_name='agent_policies')
    op.drop_index(op.f('ix_deployments_workspace_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_ai_mode_configs_workspace_id'), table_name='ai_mode_configs')
    op.drop_index(op.f('ix_ai_mode_configs_id'), table_name='ai_mode_configs')
    op.drop_table('ai_mode_configs')
    # ### end Alembic commands ###
