[mypy]
python_version = 3.12
warn_return_any = False
warn_unused_configs = True
ignore_missing_imports = True
check_untyped_defs = False
disallow_untyped_defs = False
follow_imports = silent
disable_error_code = arg-type, assignment, var-annotated, union-attr, type-var, operator, attr-defined, misc, dict-item

[mypy-app.db.models]
ignore_errors = True

[mypy-razorpay.*]
ignore_missing_imports = True

