-- ==============================================================================
-- SHOPMATE AAAS - LEAST PRIVILEGE APPLICATION DATABASE ROLE SETUP
-- Enforces PostgreSQL Row-Level Security (RLS) by ensuring the app role
-- is NEVER a superuser and does NOT possess BYPASSRLS privilege.
-- ==============================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'shopmate_app') THEN
        CREATE ROLE shopmate_app WITH LOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOINHERIT PASSWORD 'shopmate_app_secure_pass_2026';
    ELSE
        ALTER ROLE shopmate_app WITH NOSUPERUSER NOBYPASSRLS;
    END IF;
END $$;

-- Grant schema permissions
GRANT USAGE ON SCHEMA public TO shopmate_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO shopmate_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO shopmate_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO shopmate_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO shopmate_app;

-- Force RLS on all tenant-isolated tables even if owner or table creator touches them
ALTER TABLE IF EXISTS products FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS orders FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_items FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS carts FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS cart_items FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS customers FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS knowledge_sources FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS knowledge_docs FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS knowledge_chunks FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ai_mode_configs FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS deployments FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS idempotency_keys FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS audit_logs FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS subscriptions FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS invoices FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS usage_records FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS workspace_invitations FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS api_keys FORCE ROW LEVEL SECURITY;
